// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CursorPosition } from "./CursorPosition";

export type CursorPositions = { raw: CursorPosition, mapped: CursorPosition, };
