// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DisplayData = { screen_width: number, screen_height: number, monitor_scale_factor: number, };
