// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserProfile } from "./UserProfile.js";
import type { FriendshipResponseDto } from "./FriendshipResponseDto.js";

export type AppData = {
  user: UserProfile | null;
  friends: Array<FriendshipResponseDto> | null;
};
