// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata for the currently active application, including localized and unlocalized names, and an optional base64-encoded icon.
 */
export type AppMetadata = { localized: string | null, unlocalized: string | null, appIconB64: string | null, };
