// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserBasicDto } from "./UserBasicDto";

export type FriendshipResponseDto = { id: string, friend: UserBasicDto | null, createdAt: string, };
