// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DollDto } from "./DollDto";

export type FriendActiveDollChangedPayload = { friendId: string, doll: DollDto | null, };
