// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserStatusPayload } from "./UserStatusPayload";

export type FriendUserStatusPayload = { userId: string, status: UserStatusPayload, };
