// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InteractionPayloadDto = { senderUserId: string, senderName: string, content: string, type: string, timestamp: string, };
