// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PresenceStatus = { title: string | null, subtitle: string | null, graphicsB64: string | null, };
