// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresenceStatus } from "./PresenceStatus";
import type { UserStatusState } from "./UserStatusState";

export type UserStatusPayload = { presenceStatus: PresenceStatus, state: UserStatusState, };
